export const STORE_ANSWER = 'STORE_ANSWER';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_OFFENDER_NOMIS_PROFILES = 'GET_OFFENDER_NOMIS_PROFILES';
export const GET_VIPER_SCORES = 'GET_VIPER_SCORES';
export const SELECT_OFFENDER = 'SELECT_OFFENDER';