export default {
  SIGN_IN: '/sign-in',
  BEFORE_YOU_START: '/before-you-start',
  ASSESSMENT: '/assessment',
  HEALTHCARE_ASSESSMENT: '/healthcare-assessment',
  ADMIN: '/admin',
  DASHBOARD: '/dashboard',
  PRISONER_PROFILE: '/offender-profile',
  ADD_OFFENDER: '/add-offender',
  CONFIRM_OFFENDER: '/confirm-offender',
  ASSESSMENT_COMPLETE: '/assessment-complete',
  ASSESSMENT_CONFIRMATION: '/assessment-confirmation',
  FEEDBACK: '/feedback',
  FEEDBACK_CONFIRMATION: '/feedback-confirmation',
  HEALTHCARE_SUMMARY: '/healthcare-summary',
  HEALTHCARE_COMPLETE: '/healthcare-complete',
};
